### ISSUE TITLE
Why the form submission miss value from input type select if I remove the default <option /> tag

### ISSUE THREAD

**Issue by mdsaon** [redux-form/redux-form#4651] opened 2020-04-08 18:05 UTC
I have the following form component and when I have removed the <option />,I am not getting the value of "level" after submitting the form.

`import React, {useState} from 'react'
import { Field, reduxForm } from 'redux-form'

const AddNewForm = props => {
  const [selected,setSelected]=useState('');
  const { handleSubmit, pristine, reset, submitting } = props
  const items = [
    { country: "USA", level: 1 },
    { country: "Canada", level: 2 },
    { country: "Bangladesh", level: 7 }
  ];

  const handleChange =(e)=>{
    setSelected(e.target.value)
  }
  return (
    <form onSubmit={handleSubmit}>
      <div>
        <label>First Name</label>
        <div>
          <Field
            name="firstName"
            component="input"
            type="text"
            placeholder="First Name"
          />
        </div>
      </div>
      <div>
        <label>Country</label>
        <div>
          <Field name="country" component="select" onChange={handleChange}>
            {Array.from(new Set(items.map((item)=>item.country))).map((country, index) => (
                <>
                <option value={country} >{country}</option>
                </>
              ))}
          </Field>
        </div>
      </div>
      <div>
        <label>Level</label>
        <div>
          <Field name="level" component="select">
                {items.filter((item)=>item.country===selected).map((item, index) => (
                <option value={item.level}>{item.level}</option>
              ))}
          </Field>
        </div>
      </div>
      <div>
        <button type="submit" disabled={pristine || submitting}>
          Submit
        </button>
        <button type="button" disabled={pristine || submitting} onClick={reset}>
          Clear Values
        </button>
      </div>
    </form>
  )
}

export default reduxForm({
  form: 'simple' // a unique identifier for this form
})(AddNewForm)
`

**Comment by iamandrewluca** [comment] 2020-04-08 21:46
Close as duplicate of #4649

**Closed by iamandrewluca** 2020-04-08 21:46 UTC
