### ISSUE TITLE
Release 8.3.1 should only fix addition of immutable.js issue 4519

### ISSUE THREAD

**Issue by DavidOrchard** [redux-form/redux-form#4613] opened 2020-02-24 17:57 UTC
### Subject of the issue

https://github.com/redux-form/redux-form/issues/4519 is preventing us from upgrading redux and redux-form as we can't afford the bundle size increase from immutable js.  Release 8.3.1 https://github.com/redux-form/redux-form/milestone/6 is scheduled to have the fix, but it has been open for quite some time and is only 11% complete.  Could you please release just 4519 in 8.3.1 and make 8.3.2 the rest of 8.3.1 scope?

Sorry to make bug for this, as a bug in release scope is a bit unconventional, but I didn't see where else to post.

### Your environment

- **OS**: Mac, etc.
- **Packages**: redux v4, redux-form 8.3.0
- **Env**: node 12.

### Steps to reproduce
Please see bug #4519 
### Expected behaviour

Please see bug #4519 

### Actual behaviour

Please see bug #4519

**Comment by renatoagds** [comment] 2020-02-24 21:26
Duplicate of #4519

**Closed by renatoagds** 2020-02-24 21:26 UTC
Labels: bug

**Comment by DavidOrchard** [comment] 2020-02-24 21:31
This is not a duplicate of 4519.  It's a bug in release 8.3.1 scope.  You marked it as dup, closed it, and did not respond to the implied question about where is the correct place to post bugs about release scope.
