### ISSUE TITLE
Jest snapshot  component which contains redux-form will cause memory leak

### ISSUE THREAD

**Issue by wenjoy** [redux-form/redux-form#4597] opened 2020-01-12 03:19 UTC
## environment 
"jest": "24.9.0",
"redux": "4.0.4",
"redux-form": "8.2.6",
"react": "16.9.0",
"react-redux": "7.1.1",
"react-dom": "16.9.0",
nodejs version v10.15.0

## error log
```
<--- Last few GCs --->

[5438:0x102645000]    29948 ms: Mark-sweep 1395.2 (1425.0) -> 1394.7 (1425.5) MB, 1228.4 / 0.0 ms  (average mu = 0.095, current mu = 0.024) allocation failure scavenge might not succeed
[5438:0x102645000]    30917 ms: Mark-sweep 1395.9 (1426.0) -> 1395.3 (1426.0) MB, 953.2 / 0.0 ms  (average mu = 0.062, current mu = 0.017) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x28b5fdfdbe3d]
    1: StubFrame [pc: 0x28b5fdfdd3c6]
Security context: 0x1e44bcc1e6e1 <JSObject>
    2: printComplexValue(aka printComplexValue) [0x1e4471745081] [/Users/georgexie/workspace/projects/active/facility-ui-app/node_modules/pretty-format/build/index.js:~192] [pc=0x28b5fe2630f9](this=0x1e44395026f1 <undefined>,val=0x1e44f0719df9 <FiberNode map = 0x1e44f88b50b1>,config=0x1e447a03abf9 <Object map = 0x1e44384...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003b125 node::Abort() [/Users/georgexie/.nvm/versions/node/v10.15.0/bin/node]
 2: 0x10003b32f node::OnFatalError(char const*, char const*) [/Users/georgexie/.nvm/versions/node/v10.15.0/bin/node]
 3: 0x1001a8e85 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/georgexie/.nvm/versions/node/v10.15.0/bin/node]
 4: 0x1005742a2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/georgexie/.nvm/versions/node/v10.15.0/bin/node]
 5: 0x100576d75 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/georgexie/.nvm/versions/node/v10.15.0/bin/node]
 6: 0x100572c1f v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/georgexie/.nvm/versions/node/v10.15.0/bin/node]
 7: 0x100570df4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/georgexie/.nvm/versions/node/v10.15.0/bin/node]
 8: 0x10057d68c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/georgexie/.nvm/versions/node/v10.15.0/bin/node]
 9: 0x10057d70f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/georgexie/.nvm/versions/node/v10.15.0/bin/node]
10: 0x10054d054 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/georgexie/.nvm/versions/node/v10.15.0/bin/node]
11: 0x1007d4f24 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/georgexie/.nvm/versions/node/v10.15.0/bin/node]
12: 0x28b5fdfdbe3d
13: 0x28b5fdfdd3c6
```

## my code
TestForm.js
```
import React from 'react';
import { reduxForm, Field } from 'redux-form';

const SimpleForm = props => {
  const { handleSubmit, pristine, reset, submitting } = props;
  return (
    <form onSubmit={handleSubmit}>
      <div>
        <label>First Name</label>
        <div>
          <Field
            name="firstName"
            component="input"
            type="text"
            placeholder="First Name"
          />
        </div>
      </div>
      <div>
        <label>Last Name</label>
        <div>
          <Field
            name="lastName"
            component="input"
            type="text"
            placeholder="Last Name"
          />
        </div>
      </div>
      <div>
        <label>Email</label>
        <div>
          <Field
            name="email"
            component="input"
            type="email"
            placeholder="Email"
          />
        </div>
      </div>
      <div>
        <label>Sex</label>
        <div>
          <label>
            <Field name="sex" component="input" type="radio" value="male" />{' '}
            Male
          </label>
          <label>
            <Field name="sex" component="input" type="radio" value="female" />{' '}
            Female
          </label>
          <label>
            <Field name="sex" component="input" type="radio" value="other" />{' '}
            Other
          </label>
        </div>
      </div>
      <div>
        <label>Favorite Color</label>
        <div>
          <Field name="favoriteColor" component="select">
            <option />
            <option value="ff0000">Red</option>
            <option value="00ff00">Green</option>
            <option value="0000ff">Blue</option>
          </Field>
        </div>
      </div>
      <div>
        <label htmlFor="employed">Employed</label>
        <div>
          <Field
            name="employed"
            id="employed"
            component="input"
            type="checkbox"
          />
        </div>
      </div>
      <div>
        <label>Notes</label>
        <div>
          <Field name="notes" component="textarea" />
        </div>
      </div>
      <div>
        <button type="submit" disabled={pristine || submitting}>
          Submit
        </button>
        <button type="button" disabled={pristine || submitting} onClick={reset}>
          Clear Values
        </button>
      </div>
    </form>
  );
};

export default reduxForm({
  form: 'simple', // a unique identifier for this form
})(SimpleForm);

// If export this, everything is fine.
// export default function FF() {
//   return <div>test</div>;
// }
```

TestForm.test.js

```
import React from 'react';
import { mount } from 'enzyme';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import TestForm from './TestForm';

it('should render component properly', () => {
  const wrapper = mount(
    <Provider store={createStore(() => ({}))}>
      <TestForm />
    </Provider>,
  );
  expect(wrapper).toMatchSnapshot();
});

```

**Comment by zazapeta** [comment] 2020-01-16 22:23
Hi,
Maybe you should register the form reducer : 
 
```js
import React from 'react';
import { mount } from 'enzyme';
import { Provider } from 'react-redux';
import { createStore, combineReducers } from 'redux';
import { reducer as formReducer } from 'redux-form'
const rootReducer = combineReducers({
  form: formReducer
})
import TestForm from './TestForm';

it('should render component properly', () => {
  const wrapper = mount(
    <Provider store={createStore(rootReducer)}>
      <TestForm />
    </Provider>,
  );
  expect(wrapper).toMatchSnapshot();
});
```
no ?
P.S: 
 I didn't try

**Comment by diecastro** [comment] 2020-04-04 05:54
> Hi,
> Maybe you should register the form reducer :
> 
> ```js
> import React from 'react';
> import { mount } from 'enzyme';
> import { Provider } from 'react-redux';
> import { createStore, combineReducers } from 'redux';
> import { reducer as formReducer } from 'redux-form'
> const rootReducer = combineReducers({
>   form: formReducer
> })
> import TestForm from './TestForm';
> 
> it('should render component properly', () => {
>   const wrapper = mount(
>     <Provider store={createStore(rootReducer)}>
>       <TestForm />
>     </Provider>,
>   );
>   expect(wrapper).toMatchSnapshot();
> });
> ```
> 
> no ?
> P.S:
> I didn't try

I tried that and it didn't work, my setup is the following

-     "jest": "^25.2.7",
-     "redux": "^3.7.2",
-     "redux-form": "^8.3.2"
-     "react": "^16.13.1",
-     "react-redux": "^7.2.0",
-     nodejs version v10.15.3

**Comment by iamandrewluca** [comment] 2020-04-09 20:05
@wenjoy @diecastro we can't assume this is a issue with redux-form, here you try to snapshot a redux-form that is wrapped by enzyme, that is using redux, react-redux, react, react-dom.

I tried but could not reproduce with exact specified versions.
With a good example that will point exactly that redux-form is the issue we can't start investigating this.

Can please try to reproduce it again? Or create a repo example, so we could reproduce also.

I see in your logs `pretty-format` are you sure you running tests correctly?

I'll close this for now. Feel free to comment.

**Closed by iamandrewluca** 2020-04-09 20:05 UTC
Labels: Version 8
