### ISSUE TITLE
clearFields doesn't clear field value

### ISSUE THREAD

**Issue by lynkx** [redux-form/redux-form#4101] opened 2018-06-22 21:57 UTC
### Are you submitting a **bug report** or a **feature request**?

Bug.

### What is the current behavior?

If a form is initialized from state, then a call to clearFields doesn't do anything.

### What is the expected behavior?
clearFields should clear field values specified in parameters.

### Sandbox Link

https://codesandbox.io/s/8lq6w36xkl

### What's your environment?

redux-form 7.4.2 (but it's working for 7.3.0 https://codesandbox.io/s/42mjmk0mxw)

**Comment by lynkx** [comment] 2018-06-30 22:50
Seems like it was introduced in a97606fee0ed365903fff80cc93956fe2313a3ce

**Comment by Conmiro** [comment] 2018-07-03 14:41
We also started experiencing this when upgrading to 7.4.2, and confirmed this behavior was not occurring on 7.3.0.

**Comment by klacointe** [comment] 2018-07-31 11:15
Same issue here on 7.4.2

**Comment by mdavid88** [comment] 2018-08-14 20:31
I'm also seeing this in 7.4.2

**Comment by resistancet9** [comment] 2018-08-22 20:18
import { reset } from "redux-form";
`this.props.dispatch(reset("form_name"));`

hope this helps

**Comment by pidov** [comment] 2018-09-03 06:52
+1, really annoying

@resistancet9 your proposed solution resets the whole form. ```clearfields```on the other hand accepts a collection of fields to be reset.

**Comment by ndr80** [comment] 2018-09-04 10:27
I think you can reset a single field using `change` 
`this.props.change("fieldName", null);`

**Comment by melbon** [comment] 2018-09-25 09:17
Any updates when the fix will be released?

**Comment by zijian-etc** [comment] 2018-10-05 14:05
To fix the issue: use redux-form 7.2.0
redux-form sucks

**Comment by ketysek** [comment] 2018-10-09 12:15
Also, why it doesn't accept fields as array? I think it's confusing now, I have to add multiple fields to clear as strings separated by commas

**Comment by franleplant** [comment] 2018-10-11 15:56
Experiencing this too after upgrading to 7.4.2

**Comment by johnmanong** [comment] 2018-11-14 23:00
After digging around the code for 7.4.2, it looks like this only works if the [initial value is undefined](https://github.com/erikras/redux-form/blob/master/src/createReducer.js#L51-L55). Otherwise, it has no effect.

**Comment by Draccan** [comment] 2018-12-06 15:30
@erikras is this the right behaviour or it's a bug due to the code reported by @johnmanong ?

**Comment by DragosPaul95** [comment] 2019-02-22 17:12
Are there any updates to this? Has the issue been solved in any of the newer releases?

**Comment by mjvalade** [comment] 2019-02-25 18:40
I'm on `7.4.2` and this will clear all the fields in a form _except_ the Field `type="text"` being used as a date input. It does have a mask on it so that it formats as `mm/dd/yyyy` so maybe that is interfering? Doesn't seem like it should matter.

**Comment by glasseyes42** [comment] 2019-03-04 09:43
experiencing on 8.1.0

**Comment by Hazantip** [comment] 2019-03-05 13:26
experiencing on 8.1.0 also. doesn't clear if value was initialized via **initialValues**

**Comment by glasseyes42** [comment] 2019-03-05 13:34
I have got around this by using the `change` action creator and setting the field(s) to `''` (or initial values etc) as @ndr80 has mentioned previously. At least I can still control the form data as needed...

**Comment by Madsim** [comment] 2019-03-26 16:12
Got issues with this as well. Output values contain initialValues regardless of clearFields. Searching the web shows that there clearly is a demand for something like "clearOnUnmount" [medium solution](https://github.com/eliseumds/medium-support/blob/f877628ad3ad30ed52609d0492f3a5e31f027743/forms-at-scale-2-years-of-redux-form/Field.js). I wrote my own decorator for this and now I'm stuck because the actions are not working as expected.

**Comment by tnrich** [comment] 2019-04-18 18:45
@ms88privat and @erikras it looks like your work on https://github.com/erikras/redux-form/pull/3619 caused a fairly major regression! Can you please fix that breaking functionality so that clearFields will work as expected again. It is very confusing currently

**Comment by gitowiec** [comment] 2019-04-29 13:56
Is it fixed yet? I am experiencing this issue with `"redux-form": "7.4.2"` and I don't know if I should update, Does newest version resolves this issue?

**Comment by antokara** [comment] 2019-05-01 19:07
I'm still having this issue with the latest version 8.2.0

**Comment by iRyusa** [comment] 2019-05-05 23:34
@ms88privat & @erikras any comment on this ?

 I would like to help working on a fix but don't really understand how can this happen, looks like the `deleteInWithCleanUp` has a weird behavior now. 

I'm trying to reproduce the behavior in a test case, but don't have any luck yet :(

**Comment by hugojanruiter** [comment] 2019-06-27 23:11
I have created a pull request to fix the issue. It basically copies the logic from resetSection to clear to initial values. That is the desired behaviour right?
See: https://github.com/erikras/redux-form/pull/4498

**Closed** 2019-11-28 10:22 UTC
Labels: bug

**Comment by ajkl2533** [comment] 2020-06-12 09:26
@hugojanruiter @iamandrewluca 
I would say this issue is still not solved since there is no way how to actually clear initial value with `clearFields` action creator. You only add this buggy behaviour into the docs. I would like to know if you are planning to fix this bug or not.

**Comment by brunsmartcare** [comment] 2020-11-04 18:48
Use spread dispatch(clearFields('nameForm', true, true, ...['nameField', 'nameField']));

**Comment by 20DollarsBoots** [comment] 2020-11-04 18:53
Use spread dispatch(clearFields('nameForm', true, true, ...['nameField', 'nameField']));

**Comment by oguzhancelikarslan** [comment] 2020-11-28 22:07
I have fixed this with a workaround with the help of useState 👍 
firstly define a state veriable   const [submitSucceededState, setSubmitSucceededState] = useState(false) in your form component.

then change your form's return like below

  return (<form onSubmit={handleSubmit(formSubmit)}>
    {submitSucceededState && <Alert color="success" text="your message here." />}
    <Field component={renderField} label="Username" name="username" type="text" placeholder="Username" />
    <Button color="primary" disabled={submitting} className="btn-block">Sign Up</Button>
  </form>)


the last piece of the code block is just for defining the formSubmit function. 

lastly, put the below code into your function based component.
  const formSubmit = () => {
    if (submitSucceeded) {
      setSubmitSucceededState(true)
      reset()
    }
  }


in this way, after making successful form submission, you save the successful result in a state. Then reset your form. If you want to use this result somewhere you can use your state in your component or transfer it via props.

**Comment by wayAffirm** [comment] 2020-12-10 19:28
> Use spread dispatch(clearFields('nameForm', true, true, ...['nameField', 'nameField']));

Yeah after looking into the transpiled version of `clearFields()`, looks like you would have to pass in at least 4 arguments like this: `clearFields(formName, keepTouched, persistentSubmitErrors, fieldName, fieldName, fieldName, etc...)`. See that the fieldNames are not in an array?

From the source code, the definition looks fine, and is expecting an array `fieldNames`. So maybe the redux-form team needs to fix how they transpile their js code?
