### ISSUE TITLE
ReduxForm textarea does not work with Grammarly Chrome extention

### ISSUE THREAD

**Issue by a-amir01** [redux-form/redux-form#3889] opened 2018-03-04 22:14 UTC
### What is the current behavior?
When using ReduxForm with Grammarly Chrome extension on a textarea field, the form does not register the change Grammarly injects into the textarea field. The ```@@redux-form/CHANGE``` action does not get dispatched when using the chrome extension. 

![reduxform](https://user-images.githubusercontent.com/15374718/36951161-2ccacd7c-1fb5-11e8-9297-923afb74298a.gif)

### What is the expected behavior?
When there is a grammar error in a textarea, the user should be able to use Grammarly Chrome extension to automatically fix the grammar error.

### What's your environment?
"redux-form": "^7.2.3"
MacOSx
node: v6.10.3

I was able to reproduce the problem on the ReduxForm demo page [https://redux-form.com/7.3.0/examples/initializefromstate/](url) using Google Chrome with Grammarly Chrome extension enabled

**Comment by blacktaxi** [comment] 2018-07-02 16:56
Hi @a-amir01, I'm a dev for the Grammarly extension.

This is happening because Grammarly changes the `textarea` node's `value` property, which is not DOM-observable. So `redux-form` can not see the change happening neither by subscribing to `change` or `input` events, nor by using a `MutationObserver`. In that case, I don't believe that a good fix can be done on the `redux-form` side, aside from polling the textarea's value repeatedly.

Fortunately there is another way to achieve the same behavior on Grammarly's side through a `document.execCommand('insertText', ...)` call. We will be working on a fix. I can not give an ETA for now, but I'll try to keep this thread updated.

**Comment by gustavohenke** [comment] 2018-07-03 00:51
Amazing news @blacktaxi. Thanks for helping us with this one!

**Comment by blacktaxi** [comment] 2018-07-30 04:02
Hi @GregBrine, there wasn't a widely available update so far – we are still testing the new implementation. In the interim, I can suggest to put a `data-gramm="false"` attribute on any `textarea` or `<div contenteditable="true" />` you want to keep Grammarly from integrating with.

**Comment by omariqbalnaru** [comment] 2018-08-21 10:06
@blacktaxi any update on this?

**Comment by baash05** [comment] 2018-10-10 12:11
Same question.  Just looking for an update.

**Comment by Reflex-Gravity** [comment] 2019-04-01 10:08
Any update or fix for this issue yet?

**Comment by iamandrewluca** [comment] 2020-04-01 04:25
I'll close this one because the issue is not on this library ground.

**Closed by iamandrewluca** 2020-04-01 04:25 UTC
Labels: Version 7, bug, help wanted
