### ISSUE TITLE
Uncaught SubmissionError in dependent package

### ISSUE THREAD

**Issue by k4st0r42** [redux-form/redux-form#4162] opened 2018-08-08 07:49 UTC
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

If I throw a SubmissionError in a dependent module (by a function imported), it is not catched in the principal module.
Error message : Uncaught (in promise)

If I manually catch it, "error instanceof SubmissionError" returns false, why ??

If I throw a SubmissionError in the same module (same code, same function, I just moved it), it works.
"error instanceof SubmissionError" returns true.

### What is the expected behavior?

The SubmissionError throwed from dependent module need to be catched in the principal module as a SubmissionError to be in the validation workflow.

### What's your environment?

Chrome browser
redux-form 7.4.2
react 15.6.2
redux 3.7.2
react-redux 5.0.7

**Comment by k4st0r42** [comment] 2018-08-08 08:31
Gustavo, I don't know how to make sandbox because in this case, I need two modules with a dependency between them. Is it possible with a sandbox ?

**Comment by Dman757** [comment] 2018-09-18 23:04
Is this what you're looking for in terms of sandbox: https://codesandbox.io/s/8on6qk15j

Found here: https://github.com/erikras/redux-form/issues/1297#issuecomment-358976821

**Comment by anuraaga** [comment] 2018-09-20 10:53
I've ran into the error too in a typescript project with `esModuleInterop` set.

```ts
import { SubmissionError} from 'redux-form';
...
throw new SubmissionError()
```

does not pass the `instanceof` check but

```ts
import SubmissionError from 'redux-form/lib/SubmissionError`
...
throw new SubmissionError()
```

does. I guess it's something to do with typescript, or modules, or webpack. I guess it means `instanceof` isn't safe to use in a JS library- it's probably safer exporting a magic number field in the object or just skip the `instanceof` check and be satisfied by the presence of the `errors` field which seems enough to me.

**Comment by anuraaga** [comment] 2018-09-20 10:55
Oh - I found this is a dupe of #4092 and there is already a PR #4162 that's LGTM'd. Can it be merged?

**Closed** 2020-04-10 10:29 UTC
Labels: Version 7, needs sandbox

**Comment by iamandrewluca** [comment] 2020-04-12 11:50
Fixed in https://github.com/redux-form/redux-form/releases/tag/v8.3.4
